/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 zis_150.glb 
Author: mamont nikita (https://sketchfab.com/mamontnikita62)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zis-150-983a0ebdd79b467ea1efffdb43cb8ddf
Title: Zis 150
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/zis_150.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.WraithMesh00} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.WraithMesh01} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.WraithMesh02} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.WraithMesh03} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.WraithMesh04} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.WraithMesh05} skeleton={nodes.Object_17.skeleton} />
        <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.WraithMesh06} skeleton={nodes.Object_19.skeleton} />
        <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.WraithMesh07} skeleton={nodes.Object_21.skeleton} />
      </group>
    </group>
  )
}

// useGLTF.preload('/zis_150.glb')
